export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD'
export const RESET_USER_PASSWORD_CLEAR = 'RESET_USER_PASSWORD_CLEAR'

export const RESET_PAGE_PROFILE = 'RESET_PAGE_PROFILE'
export const RESET_PAGE_PROFILE_LOADING = 'RESET_PAGE_PROFILE_LOADING'
export const RESET_PAGE_PROFILE_ERROR = 'RESET_PAGE_PROFILE_ERROR'

export const RESET_PROFILE_TIMELINE = 'RESET_PROFILE_TIMELINE'
export const RESET_PROFILE_TIMELINE_LOADING = 'RESET_PROFILE_TIMELINE_LOADING'
export const RESET_PROFILE_TIMELINE_ERROR = 'RESET_PROFILE_TIMELINE_ERROR'
